version: '3.8'

services:
  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d hello_todo -U hello_todo" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hello_todo
      POSTGRES_USER: hello_todo
      POSTGRES_DB: hello_todo

  web:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      network: host
    ports:
      - "8080:8080"
    command: bash -c "python3 manage.py migrate && gunicorn config.wsgi:application -b 0.0.0.0:8080"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    depends_on:
      - web

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - nginx

volumes:
  db: {}